### ISSUE TITLE
Call to undefined method Contributte\Mail\Mailer\SendmailMailer::onSend

### ISSUE THREAD

**Issue by demmmmios** [contributte/mail#28]
Ahoj,

s nette/mail verzí 4 se odebralo use Nette\SmartObject a přestaly fungovat magic metody a konkrétně tenhle řádek pak háže fatal error https://github.com/contributte/mail/blob/4eb695a91993a3ae29f67b9b645ec399fb51e3a5/src/Mailer/SendmailMailer.php#L35

Call to undefined method Contributte\Mail\Mailer\SendmailMailer::onSend

**Comment by f3l1x** [comment]
Ahoj, diky za report. Opravim.
